source 'https://github.com/CocoaPods/Specs'

platform :ios, '<%= deployment_target %>'
use_frameworks!
inhibit_all_warnings!

abstract_target '<%= project_name %>Common' do
  RxSwiftVersion = '3.6'

  target '<%= project_name %>' do end
    pod 'Alamofire',             '~> 4.5'
    pod 'AlamofireObjectMapper', '~> 4.0'

    pod 'Moya',                  '~> 9.0'
    pod 'Moya/RxSwift'
    pod 'Moya-ObjectMapper',     '~> 2.2'

    pod 'RxSwift',               "~> #{RxSwiftVersion}"
    pod 'RxCocoa',               "~> #{RxSwiftVersion}"

    pod 'R.swift',               '~> 3.3'
    pod 'Fabric',                '~> 1.6'
    pod 'Crashlytics',           '~> 3.8'
    pod 'Sourcery',              '~> 0.9'

    target 'Tests' do     
      pod 'Nimble',     '~> 7.0'
      pod 'Quick',      '~> 1.1'
      pod 'RxBlocking', "~> #{RxSwiftVersion}"
    end
end

<% if enable_settings && dependency_manager_enabled?("cocoapods") %>
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['SWIFT_VERSION'] = '3.2'    
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.2'        
    end
  end
end
<% end %>
